### PR TITLE
Remove reconnection listener when closing the connection manager.

### PR DESCRIPTION
**Pull request by msvab**

### CODE REVIEW

**Comment by msvab** [comment]
The issue is that when you call `close()` on the connection manager, it triggers the reconnection logic. This PR fixes issue #48.

Please let me know, if it needs any changes.

**Comment by jwalton** [comment]
Thanks for this!  We are using semantic-release on this package, so if you could `git commit --amend` and change your commit message to:

"fix:  Remove reconnection listener when closing the connection manager."

Then I can merge this (or I can fix the comment with a squash merge, but then you won't get credit for the fix).

**Comment by msvab** [comment]
Done!

**Comment by jwalton** [comment]
Thanks!

**Pull request merged**
